version: '3.9'
services:
  # Bank Service
  atm-bank-management-service:
    build:
      context: ../ATM-bank-management-service/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-bank-management-service:1.0.2
    ports:
      - '8889:8889'
    restart: on-failure
    depends_on:
      - atm-kafka
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-bank-management-service.env

  # Account Service
  atm-account-management-service:
    build:
      context: ../ATM-account-managment-service/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-account-management-service:1.0.2
    ports:
      - '8887:8887'
    restart: on-failure
    depends_on:
      - atm-kafka
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-account-management-service.env

## User Management Service
  atm-user-management-service:
    build:
      context: ../ATM-user-management-service/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-user-management-service:1.0.3
    ports:
      - '8884:8884'
    restart: on-failure
    depends_on:
      - atm-kafka
      - atm-config-server
      - atm-zipkin
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://atm-config-server:8881/actuator/health" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-user-management-service.env

#  # Transaction Management Service
  atm-transaction-management-service:
    build:
      context: ../ATM-transaction-management-service/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-transaction-management-service:1.0.3
    ports:
      - '8888:8888'
    restart: on-failure
    depends_on:
      - atm-kafka
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-transaction-management-service.env

# # Notification Service
  atm-notification-service:
    build:
      context: ../ATM-notification-service/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-notification-service:1.0.2
    ports:
      - '8886:8886'
    restart: on-failure
    depends_on:
      - atm-kafka
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-notification-service.env

# # Log Management Service
  atm-log-management-service:
    build:
      context: ../ATM-log-management-service/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-log-management-service:1.0.2
    ports:
      - '8885:8885'
    restart: on-failure
    depends_on:
      - atm-log-management-service-db
      - atm-kafka
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-log-management-service.env

  atm-log-management-service-db:
    image: 'mongo:latest'
    restart: always
    environment:
      - 'MONGO_INITDB_DATABASE=atm-log-management-service-db'
      - 'MONGO_INITDB_ROOT_USERNAME=admin'
      - 'MONGO_INITDB_ROOT_PASSWORD=admin'
    ports:
      - '4445:27017'



## Discovery Server
  atm-discovery-server:
    build:
      context: ../ATM-discovery-server/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-discovery-server:1.0.2
    ports:
      - '8882:8882'
    restart: on-failure
    depends_on:
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-discovery-server.env

## Config Server
  atm-config-server:
    build: ../ATM-config-server
    image: amtrbouaro/atm-config-server:1.0.2
    ports:
      - '8881:8881'
    restart: on-failure
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-config-server.env

#  # API Gateway
  atm-api-gateway:
    build:
      context: ../ATM-api-gateway/
      dockerfile: Dockerfile
    image: amtrbouaro/atm-api-gateway:1.0.3
    ports:
      - '8883:8883'
    restart: on-failure
    depends_on:
      - atm-config-server
    networks:
      - atm-microservice-network
    env_file:
      - ./env/atm-api-gateway.env

#
  atm-zipkin:
    image: openzipkin/zipkin
    container_name: atm-zipkin
    ports:
      - 9490:9411
    networks:
      - atm-microservice-network

  atm-prometheus:
    image: prom/prometheus:latest
    container_name: atm-prometheus
    restart: unless-stopped
    ports:
      - '9491:9090'
    volumes:
      - ./data/prometheus/config/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    networks:
      - atm-microservice-network

  atm-grafana:
    image: grafana/grafana:latest
    container_name: atm-grafana
    restart: unless-stopped
    ports:
      - '9492:3000'
    depends_on:
      - atm-prometheus
    volumes:
      - ./data/grafana/config:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOWS_SIGN_UP=false
      - GF_SERVER_DOMAIN=localhost
      - GF_LOG_MODE=console file
    networks:
      - atm-microservice-network

  atm-kafka:
    image: landoop/fast-data-dev:latest
    container_name: atm_kafka
    ports:
      - 3181:3181
      - 3040:3040
      - 7082:7082
      - 7083:7083
      - 9092:9092
    environment:
      ADV_HOST: atm-kafka
      RUNTESTS: 0
      SAMPLEDATA: 0
      BROKER_PORT: 9092
      REST_PORT: 7082
      CONNECT_PORT: 7083
      ZK_PORT: 3181
      WEB_PORT: 3040
      REGISTRY_PORT: 8081
    restart: unless-stopped
    networks:
      - atm-microservice-network

  atm-zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
  atm-broker:
    image: confluentinc/cp-kafka:7.0.1
    container_name: broker
    ports:
      - "9093:9092"
    depends_on:
      - atm-zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://broker:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

networks:
  atm-microservice-network:
    driver: bridge